FROM node:21-alpine AS base

WORKDIR /app/frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#FROM nginx:alpine

#COPY --from=base /app/frontend/dist /usr/share/nginx/html
#COPY --from=base /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

#CMD ["nginx", "-g", "daemon off;"]
