name: Deployment Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log In to Registry
        run: echo "${{ secrets.CONTAINER_REGISTRY_PASSWORD }}" | docker login "${{ secrets.CONTAINER_REGISTRY_NAME }}" --username "${{ secrets.CONTAINER_REGISTRY_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker build -t ghcr.io/speixoto12/spotlive-web:preview -f ./frontend/Dockerfile.prod ./frontend/
          docker push ghcr.io/speixoto12/spotlive-web:preview

          docker build -t ghcr.io/speixoto12/spotlive-api:preview -f ./backend/Dockerfile.prod ./backend/
          docker push ghcr.io/speixoto12/spotlive-api:preview